// Template for js/config.js — this file IS committed to git.
// js/config.js is gitignored and auto-generated by: node generate-config.js
//
// To set up locally:
//   1. Copy .env.example → .env and fill in GOOGLE_CLIENT_SECRET.
//   2. Run: node generate-config.js
//
// For Vercel: set GOOGLE_CLIENT_SECRET in Project Settings → Environment Variables.
window.APP_CONFIG = {
  googleClientSecret: 'YOUR_CLIENT_SECRET',
};
