/**
 * generate-config.js
 *
 * Writes js/config.js from environment variables.
 *
 * Local dev:
 *   1. Copy .env.example → .env and fill in your values.
 *   2. Run: node generate-config.js
 *   3. Start server: npx serve .
 *
 * Vercel (production):
 *   Set GOOGLE_CLIENT_SECRET in Vercel dashboard →
 *   Project Settings → Environment Variables.
 *   Vercel runs this script automatically as the build command.
 */

'use strict';

const fs = require('fs');

// Parse .env file if present (local dev)
const localEnv = {};
if (fs.existsSync('.env')) {
  fs.readFileSync('.env', 'utf8')
    .split('\n')
    .forEach(line => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) return;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      localEnv[key] = val;
    });
}

// process.env takes priority (Vercel injects it at build time)
const secret = process.env.GOOGLE_CLIENT_SECRET
  || localEnv.GOOGLE_CLIENT_SECRET
  || 'YOUR_CLIENT_SECRET';

if (secret === 'YOUR_CLIENT_SECRET') {
  console.warn('[config] WARNING: GOOGLE_CLIENT_SECRET is not set. Sign-in will not work.');
}

const output = `// AUTO-GENERATED by generate-config.js — do not edit manually.
// To regenerate: node generate-config.js
// This file is gitignored and never committed to git.
window.APP_CONFIG = {
  googleClientSecret: '${secret}',
};
`;

fs.mkdirSync('js', { recursive: true });
fs.writeFileSync('js/config.js', output, 'utf8');
console.log('[config] js/config.js written.');
